name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12 PM UTC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt -t package/
        cp src/scraper.py package/

    - name: Zip deployment package
      run: |
        cd package
        zip -r ../lambda_package.zip .

    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        function-name: "paintball-price-tracker"
        zip-file: "lambda_package.zip"
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"  # Change to your AWS region