name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt -t package/
        cp src/lambda_function.py package/

    - name: Zip deployment package
      run: |
        cd package
        zip -r ../lambda_package.zip .

    - name: Update Lambda Configuration
      run: |
        aws lambda update-function-configuration \
          --function-name paintball-price-tracker \
          --timeout 30 \
          --memory-size 512
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"

    - name: Wait for Lambda Update to Complete
      run: sleep 10

    - name: Deploy to AWS Lambda
      uses: int128/deploy-lambda-action@v1
      with:
        function-name: "paintball-price-tracker"
        zip-path: "lambda_package.zip"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"